---
- name: Create custom groups
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ custom_groups }}"

- name: Manage users
  user:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    shell: "{{ item.shell | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    groups: "{{ item.groups | join(',') | default(omit) }}"
    append: yes
  loop: "{{ users }}"
  when: item.state != 'absent'

- name: Remove users
  user:
    name: "{{ item.name }}"
    state: absent
  loop: "{{ users }}"
  when: item.state == 'absent'

- name: Add SSH keys for users
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key }}"
  loop: "{{ users }}"
  when: 
    - item.ssh_key is defined
    - item.state != 'absent'

