---
- name: Install Oh My Zsh for users
  become: yes
  shell: |
    su - "{{ item.name }}" -c 'if [ ! -d "$HOME/.oh-my-zsh" ]; then \
      wget -qO- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh -s -- --unattended; \
    fi'
  when:
    - item.state == 'present'
    - item.shell is defined
    - item.shell == '/bin/zsh'
  loop: "{{ users }}"

- name: Set Zsh for users if enabled
  user:
    name: "{{ item.name }}"
    shell: /bin/zsh
  loop: "{{ users }}"
  when:
    - item.state == 'present'
    - item.shell is defined
    - item.shell == '/bin/zsh'

